### PR TITLE
Add books

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Added a new section called ``books`` with some selected titles which are pretty interesting for any developer independent of the programming language.

### CODE REVIEW

**Comment by igortg** [comment]
Huumm... At first I though was a good idea, BUT, let me present some arguments **against** it:

 * I'd like to give this list to a newcomer at ESSS and say: _read it all_. Of course, the newcomer may take a month or two, but at the end he/she would have _checked_ all items on this list.
 * We searched for something similar before creating this list (a _must read list of dev articles_), and found none. There are many lists of _Essential Books for Dev/Programming_, so a Book list would be "just one more"
 * We can quickly evaluate unknown suggested articles/talks. This is not the case for Books (nobody would say "Hold this PR till I got time to finish the book". 😛)

Let's see what @tadeu and @nicoddemus think about it

**Comment by nicoddemus** [comment]
> I'd like to give this list to a newcomer at ESSS and say: read it all. 

I think this is the central point of the repository, as I understood it, so I agree a "books" section might be out of scope. 😁

**Comment by tadeu** [comment]
Yeah, perhaps entire books could go on a different list, like `awesome-books` :P 
But I think that individual chapters are welcome :)

**Comment by nicoddemus** [comment]
OK, let's see if we create a separate repository for that then. 👍

**Pull request closed without merging**
